work_dir: experiment/Zn_e256_p0_ns_patch1_L1
data:
  train:
    dataset:
      type: SpectralDataset2d
      data_root: data/spectral/train/reflectivity
      gt_path: data/spectral/train/labelZn.txt
      elements: Zn
      pipelines:
        - type: Pad
          size_divisor: 2
#          mode: edge
          pad_val: 0
        - type: Normalize
          scope: spatial
        - type: EasyToTensor
          mode: CHW
    dataloader:
      batch_size: 4
      shuffle: true
  val:
    dataset:
      type: SpectralDataset2d
      data_root: data/spectral/val/reflectivity
      gt_path: data/spectral/val/labelZn.txt
      elements: Zn
      pipelines:
        - type: Pad
          size_divisor: 2
#          mode: edge
          pad_val: 0
        - type: Normalize
          scope: spatial
        - type: EasyToTensor
          mode: CHW
    dataloader:
      batch_size: 4
      shuffle: false

model:
  type: ParallelChannelTransformer
  preprocessor:
    type: DWT1d
    scales: 1
    wave: haar
    padding: zero
  parallels:
    - type: ChannelTransformer
      embedding:
        type: PatchEmbedding
        img_size: 4
        patch_size: 2
        in_channel: 165
        embed_dim: 256
        norm_layer: nn.LayerNorm
      basemodule:
        type: ChannelTransformerLayer
        dim: 256
        input_resolution: 2
        depth: 2
        num_head: 16
        mlp_ratio: 2.0
        qkv_bias: true
        qk_scale: null
        drop: 0.2 # drop_rate
        attn_drop: 0.0
        drop_path_rate: 0.1
    - type: ChannelTransformer
      embedding:
        type: PatchEmbedding
        img_size: 4
        patch_size: 2
        in_channel: 165
        embed_dim: 256
        norm_layer: nn.LayerNorm
      basemodule:
        type: ChannelTransformerLayer
        dim: 256
        input_resolution: 2
        depth: 1
        num_head: 16
        mlp_ratio: 2.0
        qkv_bias: true
        qk_scale: null
        drop: 0.2 # drop_rate
        attn_drop: 0.0
        drop_path_rate: 0.1
  postprocessor:
    type: IDWT1d
    wave: haar
    in_channel: 512
    out_channel: 1

loss:
#  type: MSELoss
  type: L1Loss

optimizer:
  type: AdamW
  lr: 3.0e-4
  weight_decay: 0.01
#  type: Adam
#  lr: 0.001

scheduler:
#  type: StepLR
#  step_size: 10
#  gamma: 0.7
  type: CosineAnnealingLR
  T_max: 100
  eta_min: 1.0e-6

train:
  epoch: 100

val:
  val_freq: 1
  metric: MAE

checkpoint:
  save_freq: 100
  resume_from: null
  auto_resume: false