work_dir: experiment/Zn_e256_p0_ns_patch1_1111_wob_L1
data:
  train:
    dataset:
      type: SpectralDataset2d
      data_root: data/soil_pred/train/reflectivity
      gt_path: data/soil_pred/train/labelZn.txt
      elements: Zn
      pipelines:
        - type: Pad
          size_divisor: 2
#          mode: edge
          pad_val: 0
        - type: Normalize
          scope: spatial
        - type: EasyToTensor
          mode: CHW
    dataloader:
      batch_size: 4
      shuffle: true
  val:
    dataset:
      type: SpectralDataset2d
      data_root: data/soil_pred/val/reflectivity
      gt_path: data/soil_pred/val/labelZn.txt
      elements: Zn
      pipelines:
        - type: Pad
          size_divisor: 2
#          mode: edge
          pad_val: 0
        - type: Normalize
          scope: spatial
        - type: EasyToTensor
          mode: CHW
    dataloader:
      batch_size: 4
      shuffle: true

model:
  type: SpatialUNet
  embedding:
    type: PatchEmbedding
    img_size: 4
    patch_size: 1
    in_channel: 330
    embed_dim: 256
    norm_layer: nn.LayerNorm
#  embedding:
#    type: TokenEmbedding
#    in_channel: 330
#    embed_dim: 256
#    norm_layer: nn.LayerNorm
  basemodule:
    type: ChannelTransformerLayers
    dims: 256, 512, 512, 256
    input_resolutions: 4, 2, 2, 4
    depths: 1, 1, 1, 1
    num_heads: 8, 16, 16, 8
    mlp_ratio: 4.0
    qkv_bias: true
    qk_scale: null
    drop: 0.2 # drop_rate
    attn_drop: 0.0
    drop_path_rate: 0.2
    norm_layer: nn.LayerNorm
  downsample:
    type: PixelUnShuffle
    factor: 2
    in_channel: 256
    out_channel: 512
#  bottleneck:
#    type: ConvBottle
#    in_channel: 512
#    out_channel: 512
#  bottleneck:
#    type: LinearBottle
#    in_channel: 512
#    out_channel: 512
  upsample:
    type: PixelShuffle
    factor: 2
    in_channel: 512
    out_channel: 256
  fusion:
    type: CatConvs
    in_channels: 1024, 512
    out_channels: 512, 256
  head:
    type: FCHead
    embed_dim: 256
    pred_num: 1

loss:
#  type: MSELoss
  type: L1Loss

optimizer:
  type: AdamW
  lr: 0.0008
  weight_decay: 0.01
#  type: Adam
#  lr: 0.001

scheduler:
#  type: StepLR
#  step_size: 10
#  gamma: 0.1
  type: CosineAnnealingLR
  T_max: 100
  eta_min: 0.000001

train:
  epoch: 100

val:
  val_freq: 1
  metric: MAE

checkpoint:
  save_freq: 1
  resume_from: null
  auto_resume: false