work_dir: experiment/e512_pe_nc_patch2_1111_wob_L1

data:
  train:
    dataset:
      type: SpectralDataset2d
      data_root: data/spectral/train/reflectivity
      gt_path: data/spectral/train/label.txt
      elements: Zn, SOM
      pipelines:
        - type: Pad
          size_divisor: 2
          mode: edge
          pad_val: 0
        - type: Normalize
          scope: channel
        - type: EasyToTensor
          mode: CHW
    dataloader:
      batch_size: 4
      shuffle: true
  val:
    dataset:
      type: SpectralDataset2d
      data_root: data/spectral/val/reflectivity
      gt_path: data/spectral/val/label.txt
      elements: Zn, SOM
      pipelines:
        - type: Pad
          size_divisor: 2
          mode: edge
          pad_val: 0
        - type: Normalize
          scope: channel
        - type: EasyToTensor
          mode: CHW
    dataloader:
      batch_size: 4
      shuffle: true

model:
  type: SpatialUNet
  embedding:
    type: PatchEmbedding
    img_size: 4
    patch_size: 2
    in_channel: 330
    embed_dim: 512
    norm_layer: nn.LayerNorm
  basemodule:
    type: ChannelTransformerLayers
    dims: 512, 1024, 1024, 512
    input_resolutions: 4, 2, 2, 4
    depths: 1, 1, 1, 1
    num_heads: 8, 16, 16, 8
    mlp_ratio: 4.0
    qkv_bias: true
    qk_scale: null
    drop: 0.2 # drop_rate
    attn_drop: 0.0
    drop_path_rate: 0.2
    norm_layer: nn.LayerNorm
  downsample:
    type: PixelUnShuffle
    factor: 2
    in_channel: 512
    out_channel: 1024
#  bottleneck:
#    type: ConvBottle
#    in_channel: 1024
#    out_channel: 1024
  upsample:
    type: PixelShuffle
    factor: 2
    in_channel: 1024
    out_channel: 512
  fusion:
    type: CatConvs
    in_channels: 2048, 1024
    out_channels: 1024, 512
  head:
    type: FCHead
    embed_dim: 512
    pred_num: 2

loss:
  type: L1Loss

optimizer:
  type: AdamW
  lr: 0.001
  weight_decay: 0.01
#  type: Adam
#  lr: 0.001

scheduler:
  type: StepLR
  step_size: 20
  gamma: 0.5

train:
  epoch: 100

val:
  val_freq: 5
  metric: MAE

checkpoint:
  save_freq: 5
  resume_from: null
  auto_resume: false