work_dir: experiments/hsi_dehaze/HD/inference/DEA_Net
#sample_path: /media/mango/系统/6636数据/2/mk/dataset/GF5最终数据/test/haze/GF9.tif
#gt_path: /media/mango/系统/6636数据/2/mk/dataset/GF5最终数据/test/haze/GF9.tif
#channel_indices: [58, 37, 19]
#save_name: DEANet-HD-e60
sample_path: /media/mango/系统/6636数据/2/mk/dataset/HD/train/haze/1_15.tif
gt_path: /media/mango/系统/6636数据/2/mk/dataset/HD/train/clean/1.tif
channel_indices: [58, 37, 19]
save_name: DEA_Net-HD-e210


num_bands: &num_bands 305       # 波段数 305 197 467

model:
  type: DEANet
  in_channels: *num_bands
  base_dim: 32

checkpoint: experiments/hsi_dehaze/HD/comparison/DEA_Net/checkpoints/210.pth




