work_dir: experiments/hsi_dehaze/HD/inference/PUCCNet
#sample_path: /media/mango/系统/6636数据/2/mk/dataset/GF5最终数据/test/haze/GF9.tif
#gt_path: /media/mango/系统/6636数据/2/mk/dataset/GF5最终数据/test/haze/GF9.tif
#channel_indices: [58, 37, 19]
#save_name: PUCCNet-HD-e30
sample_path: /media/mango/系统/6636数据/2/mk/dataset/HD/train/haze/1_15.tif
gt_path: /media/mango/系统/6636数据/2/mk/dataset/HD/train/clean/1.tif
channel_indices: [58, 37, 19]
save_name: PUCCNet-HD-e120


num_bands: &num_bands 305       # 波段数 305 197 467

model:
  type: PUCCNet
  in_channels: *num_bands

checkpoint: experiments/hsi_dehaze/HD/comparison/PUCCNet/checkpoints/120.pth




