work_dir: experiment/exp
data:
  train:
    dataset:
      type: SpectralDataset2d
      data_root: data/spectral_2/trainval/reflectivity
      gt_path: data/spectral_2/trainval/gt_original.txt
      elements: SOM
      pipelines:
        - type: Pad
          size_divisor: 2
          mode: edge
          pad_val: 0
        - type: Normalize
          scope: channel
        - type: EasyToTensor
          mode: CHW
    dataloader:
      batch_size: 4
      shuffle: true
  val:
    dataset:
      type: SpectralDataset2d
      data_root: data/spectral_2/val/reflectivity
      gt_path: data/spectral_2/val/gt_val_organic.txt
      elements: SOM
      pipelines:
        - type: Pad
          size_divisor: 2
          mode: edge
          pad_val: 0
        - type: Normalize
          scope: channel
        - type: EasyToTensor
          mode: CHW
    dataloader:
      batch_size: 4
      shuffle: false

model:
  type: SimpleViT
  embedding:
    type: PatchEmbedding
    img_size: 2
    patch_size: 1
    in_channel: 147
    embed_dim: 256
    norm_layer: nn.LayerNorm
  basemodule:
    type: SimpleVisionTransformerLayer
    dim: 256
    depth: 2
    num_heads: 16
    sequence_length: 2
    qkv_bias: true
    mlp_ratio: 4.0
    cls: true
    pos: false
    dropout: 0.0
  head:
    type: FCHead
    embed_dim: 256
    pred_num: 1

loss:
  type: L1Loss

optimizer:
  type: AdamW
  lr: 5.0e-4
  weight_decay: 0.01

scheduler:
  type: StepLR
  step_size: 20
  gamma: 0.5
#  type: CosineAnnealingLR
#  T_max: 100
#  eta_min: 1.0e-7

train:
  epoch: 100
  print_freq: 5

val:
  val_freq: 1
  metric: R2

checkpoint:
  save_freq: 100
  resume_from: null
  auto_resume: false