work_dir: experiment/AVIRIS/firstTry
data:
  train:
    dataset:
      type: MultiLevelRainHSIDataset
      root_dir: /home/disk2/ZR/datasets/AVIRIS/512
      split_file: /home/disk2/ZR/datasets/AVIRIS/512/train.txt
      pipelines:
        - type: EasyToTensor
          mode: CHW
    dataloader:
      batch_size: 1
      shuffle: true
  val:
    dataset:
      type: MultiLevelRainHSIDataset
      root_dir: /home/disk2/ZR/datasets/AVIRIS/512
      split_file: /home/disk2/ZR/datasets/AVIRIS/512/val.txt
      pipelines:
        - type: EasyToTensor
          mode: CHW
    dataloader:
      batch_size: 2
      shuffle: false

num_bands: &num_bands 224       # 波段数
embed_dim: &embed_dim 16       # 传播维度

model:
  type: HDRFormer
  in_channels: *num_bands
  out_channels: *num_bands
  prior_extractor:
    type: GroupRCP
    split_bands: [50, 100, 150]
  band_selector:
    type: BCAM
    in_channels: *num_bands  # !!int *base * 2
    ratio: 0.5
    min_proj: false
  embedding_cfg:
    type: OverlapPatchEmbedding
    in_channels: *num_bands
    embed_dim: *embed_dim
    bias: false
  fusion_cfg:
    type: CatPWConvFusion
  sampling_cfg:
    downsample: PixelShuffleDownsample
    upsample: PixelShuffleUpsample
    factor: 2
  transformer_cfg:
    type: SelfCrossAttentionLayer
    num_heads: [2, 2, 2, 2]
    num_blocks: [2, 2, 2, 2]
    freq_cfg:
      type: DWT
      J: 1
      wave: haar
      mode: reflect
    prior_cfg:   # forward for prior
      type: GRCPBranch
      strategy: dilation
    sparse_strategy: MultiscaleTopK
    ffn_cfg:
      type: LeFF
      ratio: 4
      use_eca: true
    ln_bias: true





loss:
  type: L1Loss

optimizer:
  type: AdamW
  lr: 1.0e-4
  weight_decay: 0.01
#  type: Adam
#  lr: 0.001

scheduler:
  type: StepLR
  step_size: 20
  gamma: 0.5
#  type: CosineAnnealingLR
#  T_max: 100
#  eta_min: 1.0e-6

train:
  epoch: 100
  print_freq: 5

val:
  val_freq: 1
  metric: R2

checkpoint:
  save_freq: 100
  resume_from: null
  auto_resume: false