work_dir: experiment/Zn/dwt_mamba
data:
  train:
    dataset:
      type: SpectralDataset2d
      data_root: data/soil_pred/train/reflectivity
      gt_path: data/soil_pred/train/labelZn_scale.txt
      elements: Zn
      pipelines:
        - type: Pad
          size_divisor: 2
          mode: edge
          pad_val: 0
        - type: Normalize
          scope: channel
        - type: EasyToTensor
          mode: CHW
    dataloader:
      batch_size: 4
      shuffle: true
  val:
    dataset:
      type: SpectralDataset2d
      data_root: data/soil_pred/val/reflectivity
      gt_path: data/soil_pred/val/labelZn_scale.txt
      elements: Zn
      pipelines:
        - type: Pad
          size_divisor: 2
          mode: edge
          pad_val: 0
        - type: Normalize
          scope: channel
        - type: EasyToTensor
          mode: CHW
    dataloader:
      batch_size: 4
      shuffle: false

model:
  type: Parallel
  preprocessor:
    type: DWT1d
    scales: 1
    wave: haar
    padding: zero
  parallels:
    - type: Stack
      stacks:
        - embedding:
            type: PatchEmbedding
            img_size: 4
            patch_size: 1
            in_channel: 165
            embed_dim: 512
            norm_layer: nn.LayerNorm
        - basemodule:
            type: ParallelMambaBlock
            d_model: 512
            d_state: 128
            d_conv: 4
            expand: 2
            headdim: 64
#            use_mem_eff_path: false
        - head:
            type: FCHead
            embed_dim: 512
            pred_num: 1
    - type: Stack
      stacks:
        - embedding:
            type: PatchEmbedding
            img_size: 4
            patch_size: 1
            in_channel: 165
            embed_dim: 256
            norm_layer: nn.LayerNorm
        - basemodule:
            type: ParallelMambaBlock
            d_model: 256
            d_state: 128
            d_conv: 4
            expand: 2
            headdim: 64
#            use_mem_eff_path: false
        - head:
            type: FCHead
            embed_dim: 256
            pred_num: 1
  postprocessor:
    type: WeightedSum
    weights:
      - 0.8
      - 0.2

loss:
#  type: MSELoss
#  type: MultiL1Loss
#  weights:
#    - 0.8
#    - 0.2
  type: L1Loss

optimizer:
  type: AdamW
  lr: 1.0e-4
  weight_decay: 0.01
#  type: Adam
#  lr: 0.001

scheduler:
#  type: StepLR
#  step_size: 10
#  gamma: 0.5
  type: CosineAnnealingLR
  T_max: 100
  eta_min: 1.0e-5

train:
  epoch: 100
  print_freq: 5

val:
  val_freq: 1
  metric: R2

checkpoint:
  save_freq: 100
  resume_from: null
  auto_resume: false