work_dir: experiment/exp
data:
  train:
    dataset:
      type: SpectralDataset2d
      data_root: data/spectral/train/reflectivity
      gt_path: data/spectral/train/labelZn_scale.txt
      elements: Zn
      pipelines:
        - type: Pad
          size_divisor: 2
          mode: edge
          pad_val: 0
        - type: Normalize
          scope: channel
        - type: EasyToTensor
          mode: CHW
    dataloader:
      batch_size: 4
      shuffle: true
  val:
    dataset:
      type: SpectralDataset2d
      data_root: data/spectral/val/reflectivity
      gt_path: data/spectral/val/labelZn_scale.txt
      elements: Zn
      pipelines:
        - type: Pad
          size_divisor: 2
          mode: edge
          pad_val: 0
        - type: Normalize
          scope: channel
        - type: EasyToTensor
          mode: CHW
    dataloader:
      batch_size: 4
      shuffle: false

model:
  type: ParallelSpatialChannelTransformer
  embedding:
    type: PatchEmbedding
    img_size: 4
    patch_size: 2
    in_channel: 330
    embed_dim: 512
    norm_layer: nn.LayerNorm
  parallels:
    - type: Stack
      stacks:
        - basemodule:
            type: ChannelTransformerLayer
            dim: 512
            input_resolution: 2
            depth: 2
            num_heads: 16
            mlp_ratio: 2.0
            qkv_bias: true
            qk_scale: null
            drop: 0.2 # drop_rate
            attn_drop: 0.0
            drop_path: 0.1
        - head:
            type: FCHead
            embed_dim: 512
            pred_num: 1
    - type: Stack
      stacks:
        - basemodule:
            type: SwinTransformerLayer
            dim: 512
            input_resolution: 2
            depth: 1
            num_head: 16
            window_size: 2
            mlp_ratio: 2.0
            qkv_bias: true
            qk_scale: null
            drop: 0.2 # drop_rate
            attn_drop: 0.0
            drop_path: 0.1
        - head:
            type: FCHead
            embed_dim: 512
            pred_num: 1
  postprocessor:
    type: WeightedSum
    weights: 2

loss:
  type: L1Loss

optimizer:
  type: AdamW
  lr: 1.0e-3
  weight_decay: 0.01

scheduler:
  type: StepLR
  step_size: 20
  gamma: 0.5
#  type: CosineAnnealingLR
#  T_max: 100
#  eta_min: 1.0e-6

train:
  epoch: 100

val:
  val_freq: 1
  metric: R2

checkpoint:
  save_freq: 100
  resume_from: null
  auto_resume: false