work_dir: experiment/base

data:
  train:
    dataset:
      type: SpectralDataset2d
      data_root: data/spectral/train/reflectivity
      gt_path: data/spectral/train/label.txt
    dataloader:
      batch_size: 4
      shuffle: true
  val:
    dataset:
      type: SpectralDataset2d
      data_root: data/spectral/val/reflectivity
      gt_path: data/spectral/val/label.txt
    dataloader:
      batch_size: 4
      shuffle: true

model:
  type: ViT1d
  embedding:
    type: PatchEmbedding
    in_channel: 330
    embed_dim: 512
    norm_layer: nn.LayerNorm
  basemodule:
    type: BasicTransformer
    dim: 512
    depth: 4
    num_head: 8
    dim_head: 64
    mlp_dim: 1024
    dropout: 0.2 # drop_rate
  head:
    type: FCHead
    embed_dim: 512
    pred_num: 2

loss:
  type: MSELoss

optimizer:
  type: AdamW
  lr: 0.001
  weight_decay: 0.01
#  type: Adam
#  lr: 0.001

scheduler:
  type: StepLR
  step_size: 20
  gamma: 0.5

train:
  epoch: 100

val:
  val_freq: 5
  metric: MAE

checkpoint:
  save_freq: 5
  resume_from: null
  auto_resume: false