work_dir: experiments/hdr_former/AVIRIS/baseline_v2
data:
  train:
    dataset:
      type: HDF5MultiLevelRainHSIDataset
      h5_path: /home/disk2/ZR/datasets/AVIRIS/128/dataset.h5
      split_file: /home/disk2/ZR/datasets/AVIRIS/128/npy/train.txt
      pipelines:
        - type: RandomFlip
          directions: [original, horizontal, vertical, diagonal]
          probs: [0.3, 0.3, 0.3, 0.1]
        - type: RandomRotation
          angles: [0, 90, 180, 270]
          prob: 0.5
        - type: EasyToTensor
          mode: CHW
    dataloader:
      batch_size: 8
      shuffle: true
      num_workers: 8
      pin_memory: true
      persistent_workers: false
      prefetch_factor: 8
      drop_last: true
  val:
    dataset:
      type: HDF5MultiLevelRainHSIDataset
      h5_path: /home/disk2/ZR/datasets/AVIRIS/128/dataset.h5
      split_file: /home/disk2/ZR/datasets/AVIRIS/128/npy/val.txt
      pipelines:
        - type: EasyToTensor
          mode: CHW
    dataloader:
      batch_size: 8
      shuffle: false

num_bands: &num_bands 224       # 波段数
embed_dim: &embed_dim 64      # 传播维度

model:
  type: HDRFormer
  in_channels: *num_bands
  out_channels: *num_bands
  prior_extractor:
    type: GroupRCP
    split_bands: [50, 100, 150]
  prev_band_selector:
    type: BCAM
    in_channels: *num_bands
    ratio: 0.5
    min_proj: false
    act: ReLU
    residual: false
  post_band_selector:
    type: BCAM
    in_channels: *num_bands
    ratio: 0.5
    min_proj: false
    act: Sigmoid
    residual: true
  embedding_cfg:
    type: OverlapPatchEmbedding
    in_channels: *num_bands
    embed_dim: *embed_dim
    bias: false
  fusion_cfg:
    type: CatPWConvFusion
  sampling_cfg:
    downsample: PixelShuffleDownsample
    upsample: PixelShuffleUpsample
    factor: 2
  transformer_cfg:
    type: SelfCrossAttentionLayer
    num_heads: [2, 4, 4, 8]
    num_blocks: [4, 6, 6, 8]
    freq_cfg:
      type: DWT
      J: 1
      wave: haar
      mode: reflect
    prior_cfg:   # forward for prior
      type: GRCPBranch
      strategy: dilation
    sparse_strategy: MultiscaleTopK
    ffn_cfg:
      type: LeFF
      ratio: 4
      use_eca: true
    ln_bias: true
  reconstruction:
    type: FreqDecouplingReconstruction
    d: 0.4
    in_channels: *num_bands
    filter_kernel_size: 3
    filter_groups: *num_bands
    norm: GN
#  reconstruction:
#    type: HDRReconstruction
#    d: 1
#    in_channels: *num_bands

train:
  total_epoch: &total_epoch 100
  use_grad_clip: true
  print_freq: 50

  loss:
    type: MSELoss
#    type: AdaptiveSpatialSpectralLossV1
#    eps: 1.0e-6
  #  type: AdaptiveSpatialSpectralLossV2
  #  eps: 1.0e-6
  #  type: SpatialSpectralFreqLoss
  #  version: v1
  #  eps: 1.0e-6
  #  wave: haar
  #  J: 1
  #  mode: reflect

  optimizer:
    type: AdamW
    lr: 3.0e-4
    weight_decay: 1.0e-4
    betas: [ 0.9, 0.999 ]


  scheduler:
    type: LinearWarmupCosineLR
    total_epochs: *total_epoch
    warmup_epochs: 10
    warmup_start_lr: 3.0e-4
    min_lr: 1.0e-6
#    type: CosineAnnealingLR
#    T_max: 100
#    eta_min: 1.0e-6



val:
  val_freq: 1
  metric: psnr

checkpoint:
  save_freq: 10
  resume_from: null
  auto_resume: false