work_dir: experiments/hdr_former/AVIRIS/test/baseline
data:
  test:
    dataset:
      type: HDF5MultiLevelRainHSIDataset
      h5_path: /home/disk2/ZR/datasets/AVIRIS/128/dataset.h5
      split_file: /home/disk2/ZR/datasets/AVIRIS/128/npy/val.txt
      pipelines:
        - type: EasyToTensor
          mode: CHW
    dataloader:
      batch_size: 8
      shuffle: false

num_bands: &num_bands 224       # 波段数
embed_dim: &embed_dim 64      # 传播维度

model:
  type: HDRFormer
  in_channels: *num_bands
  out_channels: *num_bands
  prior_extractor:
    type: GroupRCP
    split_bands: [50, 100, 150]
  band_selector:
    type: BCAM
    in_channels: *num_bands
    ratio: 0.5
    min_proj: false
  embedding_cfg:
    type: OverlapPatchEmbedding
    in_channels: *num_bands
    embed_dim: *embed_dim
    bias: false
  fusion_cfg:
    type: CatPWConvFusion
  sampling_cfg:
    downsample: PixelShuffleDownsample
    upsample: PixelShuffleUpsample
    factor: 2
  transformer_cfg:
    type: SelfCrossAttentionLayer
    num_heads: [2, 4, 4, 8]
    num_blocks: [4, 6, 6, 8]
    freq_cfg:
      type: DWT
      J: 1
      wave: haar
      mode: reflect
    prior_cfg:   # forward for prior
      type: GRCPBranch
      strategy: dilation
    sparse_strategy: MultiscaleTopK
    ffn_cfg:
      type: LeFF
      ratio: 4
      use_eca: true
    ln_bias: true
  reconstruction:
    type: FreqDecouplingReconstruction
    d: 1
    in_channels: *num_bands
    filter_kernel_size: 3
    filter_groups: 8
    norm: GN

metric: ~
