work_dir: experiments/hsi_dehaze/AVIRIS/inference/D3
sample_path: /media/mango/系统/6636数据/2/mk/DATASET/HSIDeD-AVI/valid/hazy/2_12_1_3.mat
gt_path: /media/mango/系统/6636数据/2/mk/DATASET/HSIDeD-AVI/valid/clean/2_12_1_3.mat
channel_indices: [36, 18, 7]
save_name: D3-AVIRIS-e30

#num_bands: &num_bands 305       # 波段数 305 197 467
#
#model:
#  type: D3
#  in_channels: *num_bands
#
#checkpoint: experiments/hsi_dehaze/HD/comparison/D3/checkpoints/60.pth


num_bands: &num_bands 197       # 波段数 305 197 467

model:
  type: D3
  in_channels: *num_bands

checkpoint: experiments/hsi_dehaze/AVIRIS/comparison/D3/checkpoints/30.pth


